fragment ShoppingCart on Cart {
  id
  checkoutUrl
  lines(first: 250) {
    nodes {
      id
      merchandise {
        ... on ProductVariant {
          id
          image {
            url: url(transform: { maxWidth: 96, maxHeight: 96 })
          }
          product {
            title
          }
          selectedOptions {
            name
            value
          }
        }
      }
      cost {
        subtotalAmount {
          amount
          currencyCode
        }
        totalAmount {
          amount
          currencyCode
        }
      }
      quantity
    }
  }
  cost {
    totalAmount {
      amount
      currencyCode
    }
  }
  totalQuantity
}
